In [2]:
import numpy as np

In [4]:
from numpy import ndarray


num: np.ndarray = np.random.rand(5)
print(num)

[0.93639687 0.51753674 0.29838811 0.49678895 0.73314453]


In [4]:
num1: np.ndarray = np.random.randn(5, 4)
print(num1)

[[-1.42943069  1.87967552  0.00328086  0.94034855]
 [ 1.12869559 -1.01934296 -0.69028643 -0.72376905]
 [-0.15320331 -0.88472018 -0.13783436  0.55605964]
 [ 0.99652344  1.74217118  0.89822266 -0.05894656]
 [ 0.23825393 -0.88274793  0.396221    0.29845035]]


In [5]:
num1: np.ndarray = np.random.ranf(5)
print(num1)

[0.54548119 0.81461392 0.92817415 0.6059606  0.06186886]


In [6]:
num1: np.ndarray = np.random.randint(2, 4, 3)
print(num1)

[2 2 3]


# Data Type

In [5]:
from numpy import int8


x:np.ndarray = np.array([1.2,2,3])
print(x)
print(f"Data Type of x is: {x.dtype}")

[1.2 2.  3. ]
Data Type of x is: float64


In [6]:
x1:np.ndarray = np.int_(x)
print(x1)
print("Type of: ",x1.dtype)

[1 2 3]
Type of:  int32


In [4]:
a : np.ndarray = np.array([1, 2, 3])

print(a) #print array
display(a.dtype) #data type of array
display(a.shape) #shape of array
display(a.ndim) #number of dimensions
display(a.size) #number of elements
display(a.itemsize) #size of each element in bytes
display(a.nbytes) #number of bytes

[1 2 3]


dtype('int32')

(3,)

1

3

4

12

In [11]:
from nptyping import NDArray, Shape, Int

a1: NDArray[Shape["3,4"], Int] = np.array([[1, 2, 3,4], [4, 5, 6,8], [7, 8, 9,2]])
print(a1)
display(a1.shape)
display(a1.dtype)
display(a1.ndim)
display(a1.size)
display(a1.itemsize)

[[1 2 3 4]
 [4 5 6 8]
 [7 8 9 2]]


(3, 4)

dtype('int32')

2

12

4

In [12]:
print(a1 + 3)

[[ 4  5  6  7]
 [ 7  8  9 11]
 [10 11 12  5]]


In [13]:
%%time
a1*8

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 8, 16, 24, 32],
       [32, 40, 48, 64],
       [56, 64, 72, 16]])

In [14]:
nData: NDArray = np.arange(0, 21) #from 0 to 10 
nData

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [15]:
nData[2:7]

array([2, 3, 4, 5, 6])

In [17]:
nData[2:7] = 100
nData

array([  0,   1, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [20]:
a :NDArray = np.array([100, 20, 3])

print(a)
print(nData)

a[np.in1d(a, nData)]


[100  20   3]
[  0   1 100 100 100 100 100   7   8   9  10  11  12  13  14  15  16  17
  18  19  20]


array([100,  20])

In [26]:

np.intersect1d(a, nData)

array([ 20, 100])

In [36]:
x:NDArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y:NDArray = np.array([1, 2, 5, 4, 9, 3, 8, 7, 6, 10])

print(x)
print(y)

np.where(x < y, x,y)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  5  4  9  3  8  7  6 10]


array([ 1,  2,  3,  4,  5,  3,  7,  7,  6, 10])

In [3]:
[i for i in dir(print()) if not i.startswith("_")]
# for i in dir(print()):

[]